package:
  name: pytorch-geometric
  version: 2.3.0

source:
  url: https://files.pythonhosted.org/packages/43/b5/be9795db7756e6c1fa2606c8145ec637552487e72c6428ed0b231f8bcbd3/torch_geometric-2.3.0.tar.gz

requirements:
  host:
    - pip
    - python {{ environ.get('PYTHON_VERSION') }}

  run:
    - python {{ environ.get('PYTHON_VERSION') }}
    - {{ environ.get('CONDA_PYTORCH_CONSTRAINT') }}
    - {{ environ.get('CONDA_CUDATOOLKIT_CONSTRAINT') }}
    - psutil
    - tqdm
    - jinja2
    - pyparsing
    - numpy
    - scipy
    - requests
    - scikit-learn

build:
  string: py{{ environ.get('PYTHON_VERSION').replace('.', '') }}_torch_{{ environ['TORCH_VERSION'] }}_{{ environ['CUDA_VERSION'] }}
  script: pip install .

test:
  imports:
    - torch_geometric
    - torch_geometric.nn
    - torch_geometric.data
    - torch_geometric.utils
    - torch_geometric.datasets
    - torch_geometric.transforms

about:
  home: https://github.com/pyg-team/pytorch_geometric
  license: MIT
  summary: Graph Neural Network Library for PyTorch
