name: Full Testing

on:  # yamllint disable-line rule:truthy
  workflow_dispatch:
  schedule:
    - cron: "0 6 * * *"  # Everyday at 6:00am UTC/10:00pm PST

jobs:

  pytest:
    if: github.repository == 'pyg-team/pytorch_geometric'
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: ['3.8', '3.9', '3.10']

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup packages
        uses: ./.github/actions/setup
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install graphviz
        if: ${{ runner.os == 'Linux' }}
        run: |
          sudo apt-get install graphviz

      - name: Install main package
        run: |
          pip install -e .[full,test]

      - name: Run tests
        run: |
          FULL_TEST=1 pytest --cov --cov-report=xml
        shell: bash

      - name: Upload coverage
        uses: codecov/codecov-action@v2
        with:
          fail_ci_if_error: false
