name: Building PyG Conda

on: [workflow_dispatch]  # yamllint disable-line rule:truthy

jobs:

  conda-build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-18.04, macos-10.15, windows-2019]
        # We have troube building for Python 3.11 due to version conflicts.
        python-version: ['3.7', '3.8', '3.9', '3.10']  # '3.11'
        torch-version: [1.12.0, 1.13.0, 2.0.0]
        cuda-version: ['cpu', 'cu102', 'cu113', 'cu116', 'cu117', 'cu118']
        exclude:
          - torch-version: 1.12.0
            python-version: '3.11'
          - torch-version: 1.12.0
            cuda-version: 'cu117'
          - torch-version: 1.12.0
            cuda-version: 'cu118'
          - torch-version: 1.13.0
            python-version: '3.11'
          - torch-version: 1.13.0
            cuda-version: 'cu102'
          - torch-version: 1.13.0
            cuda-version: 'cu113'
          - torch-version: 1.13.0
            cuda-version: 'cu118'
          - torch-version: 2.0.0
            python-version: '3.7'
          - torch-version: 2.0.0
            cuda-version: 'cu102'
          - torch-version: 2.0.0
            cuda-version: 'cu113'
          - torch-version: 2.0.0
            cuda-version: 'cu115'
          - torch-version: 2.0.0
            cuda-version: 'cu116'
          - os: macos-10.15
            cuda-version: 'cu102'
          - os: macos-10.15
            cuda-version: 'cu113'
          - os: macos-10.15
            cuda-version: 'cu116'
          - os: macos-10.15
            cuda-version: 'cu117'
          - os: macos-10.15
            cuda-version: 'cu118'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Conda for Python ${{ matrix.python-version }}
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Free up disk space
        if: ${{ runner.os == 'Linux' }}
        run: |
          sudo rm -rf /usr/share/dotnet

      - name: Install Conda packages
        run: |
          conda install conda-build conda-verify --yes
        shell:
          bash -l {0}

      - name: Build Conda package
        run: |
          ./conda/pyg/build_conda.sh ${{ matrix.python-version }} ${{ matrix.torch-version }} ${{ matrix.cuda-version }}
        shell:
          bash -l {0}

      - name: Publish Conda package
        run: |
          conda install anaconda-client --yes
          anaconda upload --force --label main $HOME/conda-bld/*/*.tar.bz2
        env:
          ANACONDA_API_TOKEN: ${{ secrets.PYG_ANACONDA_TOKEN }}
        shell:
          bash -l {0}
