name: Linting

on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - master
  pull_request:

jobs:

  pyright:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup packages
        uses: ./.github/actions/setup
        with:
          full_install: false

      - name: Install pyright
        run: |
          pip install pyright

      - name: Run pyright
        continue-on-error: true
        run: |
          pyright

  pylint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4.3.0
        with:
          python-version: 3.8
          check-latest: true
          cache: pip
          cache-dependency-path: |
            setup.py

      - name: Install dependencies
        run: pip install pylint

      - name: Run linting
        continue-on-error: true
        run: pylint **/*.py

  mypy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4.3.0
        with:
          python-version: 3.8
          check-latest: true
          cache: pip
          cache-dependency-path: |
            setup.py

      - name: Install dependencies
        run: pip install mypy

      - name: Check type hints
        continue-on-error: true
        run: |
          mypy --install-types --non-interactive --ignore-missing-imports -m torch_geometric
